[boris]
  version = 1

[build.dist-7-10-core]
  command = [["master", "build", "dist-7-10", "-C", "zebra-core"]]

[build.dist-8-0-core]
  command = [["master", "build", "dist-8-0", "-C", "zebra-core"]]

[build.dist-validate]
  command = [["validate-respect"]]

[build.branches-7-10-core]
  command = [["master", "build", "branches-7-10", "-C", "zebra-core"]]

[build.branches-8-0-core]
  command = [["master", "build", "branches-8-0", "-C", "zebra-core"]]

[build.all-rebased]
  command = [["rebased"]]

[build.all-submodules]
  command = [["dangling-refs"]]
