[master]
  runner = "s3://ambiata-dispensary-v2/dist/master/master-haskell/linux/x86_64/20170104233312-ee8addd/master-haskell-20170104233312-ee8addd"
  version = 1
  sha1 = "3b707a2ba2d74ee13fe81a658bed191a5808e6f5"

[build.dist-7-10]
  GHC_VERSION = "7.10.2"
  CABAL_VERSION = "1.22.4.0"
  HADDOCK = "true"
  HADDOCK_S3 = "$AMBIATA_HADDOCK_MASTER"
  HADDOCK_URL = "$AMBIATA_HADDOCK_MASTER_URL"
  PUBLISH = "true"
  PUBLISH_S3 = "$AMBIATA_ARTEFACTS_MASTER"
  PUBLISH_EXECUTABLES = "zebra"

[build.dist-8-0]
  GHC_VERSION = "8.0.1"
  CABAL_VERSION = "1.24.0.0"

[build.branches-7-10]
  GHC_VERSION = "7.10.2"
  CABAL_VERSION = "1.22.4.0"
  HADDOCK = "true"
  HADDOCK_S3 = "$AMBIATA_HADDOCK_BRANCHES"
  HADDOCK_URL = "$AMBIATA_HADDOCK_BRANCHES_URL"
  PUBLISH = "true"
  PUBLISH_S3 = "$AMBIATA_ARTEFACTS_BRANCHES"
  PUBLISH_EXECUTABLES = "zebra"

[build.branches-8-0]
  GHC_VERSION = "8.0.1"
  CABAL_VERSION = "1.24.0.0"
